# fly.toml app configuration file generated for datingappforu on 2024-04-28T17:18:15+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'datingappforu'
primary_region = 'ams'

[build]
  image = 'boaz100/datingapp:latest'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
